import { atom, RecoilState } from 'recoil';
import { CharacterInterface } from './interfaces';

/**
 * This atom handles storing all the bookmarks.
 * Bookmarks should be generated by clicking an [Sidebar.tsx] Option.tsx
 *
 * @usedBy FrameBar.tsx
 */
export const openBookmarksAtom = atom({
	key: 'selectedCharacters',
	default: [] as CharacterInterface[],
});

/**
 * This atom handles storing the id of an active character
 * An anctive character is a character that should be displayed in the Frame.tsx
 *
 * @usedBy index.tsx
 */
export const selectedActiveCharacterAtom: RecoilState<any> = atom({
	key: 'selectedActiveCharacter',
	default: null,
});

/**
 * This atom handles storing the inputed text in a Searchbar.tsx component
 * Each Searchbar.tsx should use it's own atom
 *
 * @usedBy Sidebar.tsx
 */
export const sidebarSearchAtom = atom({
	key: 'sidebarSearchState',
	default: '',
});

/**
 * This atom handles storing the inputed text in a Searchbar.tsx component
 * Each Searchbar.tsx should use it's own atom
 *
 * @usedBy Welcome.tsx
 */
export const codeAtom = atom({
	key: 'codeState',
	default: '',
});

export const isSelectedAtom = atom({
	key: 'isSelected',
	default: '',
});

//
export const levelAtom = atom({
	key: 'levelAtom',
	default: 1,
});

export const levelTargetAtom = atom({
	key: 'levelTargetAtom',
	default: 1,
});

export const normalAtom = atom({
	key: 'normalAtom',
	default: 1,
});

export const normalTargetAtom = atom({
	key: 'normalTargetAtom',
	default: 1,
});

export const skillAtom = atom({
	key: 'skillAtom',
	default: 1,
});

export const skillTargetAtom = atom({
	key: 'skillTargetAtom',
	default: 1,
});

export const burstAtom = atom({
	key: 'burstAtom',
	default: 1,
});

export const burstTargetAtom = atom({
	key: 'burstTargetAtom',
	default: 1,
});

export const levelItemsAtom = atom({
	key: 'levelItemsAtom',
	default: [] as any[],
});

export const skillsItemsAtom = atom({
	key: 'skillItemsAtom',
	default: [] as any[],
});

export const totalItemsAtom = atom({
	key: 'totalItemsAtom',
	default: [] as any[],
});
